apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgdk-argocd-singleapp
  namespace: openshift-gitops
spec:
  destination:
    namespace: bgdk
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/bgd/overlays/bgdk
    repoURL: https://github.com/RedHat-EMEA-SSA-Team/ns-apps
    targetRevision: single-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
